# Note: Experimental transition to zensical from mkdocs and its plugins

# Fixme: Missing gen-files, mkdocstrings, snippets include, etc.
# Fixme: Extend from a base configuration when supported

[project]
site_name = "Pyaket"
site_description = "ðŸ“¦ Easy Python to Fast Executables"
site_author = "Tremeschin"
site_url  = "https://pyaket.dev/"
repo_url  = "https://github.com/BrokenSource/Pyaket/"
repo_name = "BrokenSource/Pyaket"
edit_uri  = "edit/main/website/"
copyright = "&copy; CC BY-SA 4.0, <a href='https://github.com/Tremeschin/'>Tremeschin</a> ðŸ‡§ðŸ‡·"
docs_dir  = "website"
nav = [
  {"Home" = [
    "index.md",
    {"About" = [
      "about/community.md",
      "about/contributing.md",
      "about/changelog.md",
      "about/roadmap.md",
      "about/contact.md",
      "about/mission.md",
      "about/license.md",
      "about/credits.md",
    ]}
  ]},
  {"Installation" = [
    "get/index.md",
    {"Package"=[
      "get/python.md",
      "get/release.md",
      "get/source.md",
      "get/docker.md",
    ]},
    {"Workflows"=[
      "get/ci/github.md",
      "get/ci/gitlab.md",
    ]},
    {"Tools"=[
      "get/rust.md",
    ]},
  ]},
  {"Examples" = [
    "examples/index.md",
  ]},
  {"Documentation" = [
    "docs/index.md",
    {"Configuration"=[
      "docs/project/application.md",
      "docs/project/dependencies.md",
      "docs/project/directories.md",
      "docs/project/python.md",
      "docs/project/pytorch.md",
      "docs/project/entry.md",
    ]},
    {"Rust" = [
      "docs/rust/profiles.md",
      "docs/rust/crosscompiling.md",
    ]},
    {"Extra" = [
      "docs/pinning.md",
    ]},
  ]},
  {"Questions" = [
    {"General" = [
      "faq/general.md",
      "faq/alternatives.md",
    ]},
    {"Systems" = [
      "faq/windows.md",
      "faq/linux.md",
      "faq/macos.md",
    ]},
  ]},
]

# Fixme: Common monorepo theme
extra_css = ["css/main.css"]

# ----------------------------------------------------------------------------

[project.theme]
variant = "modern"
custom_dir = "website/overrides"
favicon = "assets/images/logo.png"
language = "en"
features = [
  "announce.dismiss",

  # View or edit page source
  # "content.action.edit",
  "content.action.view",

  # Code block features
  "content.code.annotate",
  "content.code.copy",

  # Footnote preview
  "content.footnote.tooltips",
  "content.tooltips",

  # Switch all tabs with the same name at once
  "content.tabs.link",

  # Others
  "navigation.indexes",
  "navigation.expand",
  # "navigation.sections",
  "navigation.footer",
  "navigation.path",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.tabs",
  "navigation.top",
  "search.highlight",
  "toc.follow",
]

[project.extra.status]
wip = "Work in Progress"
deprecated = "Deprecated"

# ---------------------------------------------------------------------------- #

[project.markdown_extensions.pymdownx.snippets]

# Fixme: Extend from default preset (snippets)
# https://zensical.org/docs/setup/extensions/#default-configuration
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  {name="mermaid", class="mermaid", format="pymdownx.superfences.fence_code_format"}
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]

# ---------------------------------------------------------------------------- #

[project.theme.icon]
logo = "octicons/package-16"
repo = "fontawesome/brands/github"

[project.theme.font]
text = "Inter"
code = "Cascadia Code"

[[project.theme.palette]]
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
media       = "(prefers-color-scheme: light)"
scheme      = "default"
primary     = "blue"
accent      = "light-blue"

[[project.theme.palette]]
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
media       = "(prefers-color-scheme: dark)"
scheme      = "slate"
primary     = "orange"
accent      = "orange"

# ----------------------------------------------------------------------------

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"
name = "Discord"

[[project.extra.social]]
icon = "fontawesome/brands/telegram"
link = "https://t.me/BrokenSource"
name = "Telegram"

[[project.extra.social]]
icon = "fontawesome/brands/patreon"
link = "https://www.patreon.com/Tremeschin"
name = "Patreon"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"
name = "GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@Tremeschin"
name = "YouTube"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://twitter.com/Tremeschine"
name = "Twitter"
